// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

DTImage Computation(const DTImage &input,double weight);

#endif /* IT_computation_h */ 
